version: '3'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-iuran
        container_name: laravel-iuran
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
            - ./docker-config/php.ini:/etc/php7/conf.d/custom.ini
        networks:
            - mainapp
        ports:
            - 8481:8080

    npm:
        image: node:17-alpine
        container_name: npm-iuran
        restart: unless-stopped
        working_dir: /var/www/html
        entrypoint: ["npm"]
        depends_on:
        - app
        volumes:
        - ./:/var/www/html
            
networks:
    mainapp:
        name: mainapp